# Sample Config File, edit when deploying
app:
  port: 8080
  pepper: "test_pepper_dont_use"
  base_url: "test_url"
  sendgrid_key: "your_sendgrid_api_key"
database:
  host: "localhost"
  database: "pastr"
  username: "postgres"
  password: "test12345"
  port: 5432
  use_tls: false